### ISSUE TITLE
Mobile View (Reactive)

### ISSUE THREAD

**Issue by hwisu** [minSW/fzf-color-picker#1]
It would be useful if there is one. It would be helpful if it does not break on a mobile web browser.

**Comment by minSW** [comment]
@hwitticus

Hi! First, I appreciate your feedback and I am so sorry for late reply 😢

I knew my reactive web page is broken on mobile and debated myself about that problem.
However, I decided not to develop for mobile browser because I think everyone use it to apply custom color scheme on fzf of their desktop environment.

But If you think the usage on mobile browser is useful, I will reconsider it.
Thank you for your interest! 👍🏻
